package com.example.mapper;

import com.example.model.TbTestdata;
import com.example.model.TbTestdataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbTestdataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    long countByExample(TbTestdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    int deleteByExample(TbTestdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    int insert(TbTestdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    int insertSelective(TbTestdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    List<TbTestdata> selectByExample(TbTestdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    TbTestdata selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    int updateByExampleSelective(@Param("record") TbTestdata record, @Param("example") TbTestdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    int updateByExample(@Param("record") TbTestdata record, @Param("example") TbTestdataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    int updateByPrimaryKeySelective(TbTestdata record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_TESTDATA
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    int updateByPrimaryKey(TbTestdata record);
}