package com.example.model;

public class TbTestdata {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TESTDATA.ID
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_TESTDATA.NAME
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TESTDATA.ID
     *
     * @return the value of TB_TESTDATA.ID
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TESTDATA.ID
     *
     * @param id the value for TB_TESTDATA.ID
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_TESTDATA.NAME
     *
     * @return the value of TB_TESTDATA.NAME
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_TESTDATA.NAME
     *
     * @param name the value for TB_TESTDATA.NAME
     *
     * @mbg.generated Fri May 12 00:35:41 JST 2017
     */
    public void setName(String name) {
        this.name = name;
    }
}